kwis/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^team_overview.png$', views.team_overview),
    url(r'^rnd_overview.png$', views.rnd_overview),
    url(r'^ranking/$', views.ranking, name='ranking'),
    url(r'^ranking/overview.png$', views.ranking_overview),
    url(r'^round/(?P<rnd_id>[0-9]+)/$', views.rnd_detail, name='rnd_detail'),
    url(r'^round/(?P<rnd_id>[0-9]+)/result.png$', views.rnd_result),
    url(r'^team/(?P<team_id>[0-9]+)/$', views.team_detail, name='team_detail'),
    url(r'^team/(?P<team_id>[0-9]+)/result.png$', views.team_result),
    url(r'^vote/(?P<rnd_id>[0-9]+)/(?P<team_id>[0-9]+)/$', views.vote, name='vote'),
]

kwispel/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from kwis import views as kwis_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', auth_views.login, {'template_name': 'admin/login.html'}),
    url(r'^kwis/', include('kwis.urls', namespace="kwis")),
    url(r'^$', kwis_views.ranking, name='ranking'),
]

kwis/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

# These models are defined:
# - Teams participating
# - Rounds in the quiz
# - Answered score per round for each team

class QTeam(models.Model):
    # A team only needs a name for identification
    team_name = models.CharField(max_length=200, unique=True)
    def __str__(self):
        return self.team_name
    class Meta:
        verbose_name = _('Team')
        verbose_name_plural = _('Teams')

class QRound(models.Model):
    # Each round has a name and a maximal score
    round_name = models.CharField(max_length=200, unique=True)
    max_score = models.DecimalField(max_digits=6, decimal_places=1)
    def __str__(self):
        return self.round_name + ": " + str(self.max_score)
    class Meta:
        verbose_name = _('Round')
        verbose_name_plural = _('Rounds')

class QAnswer(models.Model):
    # Each answer is bound to a team, a round and contains the score for a specific team and round
    team = models.ForeignKey(QTeam)
    rnd = models.ForeignKey(QRound)
    score = models.DecimalField(max_digits=6, decimal_places=1)
    def __str__(self):
        return str(self.team) + ", " + self.rnd.round_name + ": " + str(self.score)
    class Meta:
        verbose_name = _('Answer')
        verbose_name_plural = _('Answers')

kwis/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django import forms
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import login_required

from decimal import *

from .models import QRound, QTeam, QAnswer

# Imports needed to generate graphs
import matplotlib as mpl
mpl.use('Agg') # make sure no X backend is used

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas


# Dictionary to define color usage in graphs
colors  = {'score_good': 'green',
        'score_bad': 'red',
        'empty':'lightblue'}

# Helper classes for forms
class PostedForm(forms.Form):
    score = forms.DecimalField(max_digits=6, decimal_places=1)

class ScoreForm(forms.Form):
    def __init__(self, max_value=None, *args, **kwargs):
        super(ScoreForm, self).__init__(*args, **kwargs)
        self.fields['score'] = forms.DecimalField(max_digits=6, decimal_places=1, min_value=0, max_value=max_value)

    score = forms.DecimalField(max_digits=6, decimal_places=1, min_value=0)

# Useful common functions
def get_completed_rounds():
    """
    Return a list of rounds that are completed by all teams.
    A completed round has as much elements in its qanswer_set as there are participating teams.
    """
    result = []
    for rnd in QRound.objects.all():
        if rnd.qanswer_set.count() == QTeam.objects.count():
            result.append(rnd)
    return result

def get_ranked_results(completed_rounds):
    """
    For the rounds given in completed_rounds, calculate the total score for each team.
    Then all teams are sorted on total score and are given a ranking to allow for ex aequo scores.
    """
    results = []
    for team in QTeam.objects.all():
        teamtotal = 0
        for a in team.qanswer_set.all():
            # Only add results for complete rounds
            if a.rnd in completed_rounds:
                teamtotal += a.score
        results.append((team.team_name, teamtotal))

    # Sort the results
    sorted_results = sorted(results, reverse=True, key=lambda tup: tup[1])

    rank, count, previous, ranking = 0, 0, None, []
    for key, num in sorted_results:
        count += 1
        if num != previous:
            rank += count
            previous = num
            count = 0
        ranking.append((rank, key, num))

    return ranking

def dynamic_rotation(nbObjects):
    if nbObjects <= 10:
        return "-25"
    elif nbObjects <= 20:
        return "-35"
    else:
        return "-45"

#   Initial views contain overviews only
def index(request):
    """
    List all teams and all rounds. This is the main jury view from where to add scores
    """
    round_list = QRound.objects.all()
    team_list = QTeam.objects.all()

    round_status = []
    for r in round_list:
        if r.qanswer_set.count() == team_list.count():
            # Translators: This indicates all scores for a round have been entered
            round_status.append((r, _("Complete")))
        else:
            round_status.append((r, "%d / %d" % (r.qanswer_set.count(), team_list.count())))

    team_status = []
    for t in team_list:
        subtotal = 0
        maxtotal = 0
        for ts in t.qanswer_set.all():
            subtotal += ts.score
            maxtotal += ts.rnd.max_score
        team_status.append((t, "%.1f / %.1f" % (subtotal, maxtotal), subtotal))
    team_status.sort(key=lambda tup: tup[2], reverse = True)

    context = {'round_list': round_status, 'team_list': team_status}
    return render(request, 'kwis/index.html', context)

def ranking(request):
    """
    This is the main view for contestants: ranking of teams based on their results
    """

    # First identify completed rounds.
    rnd_complete = get_completed_rounds()

    if len(rnd_complete) == QRound.objects.count():
        # Translators: This indicates all scores for all rounds have been entered
        caption = _("Final ranking")
    elif len(rnd_complete) == 0:
        # Translators: This indicates no round has all scores entered
        caption = _("No results yet")
    else:
        caption = _("Ranking after ")
        for rnd in rnd_complete:
            caption += rnd.round_name + ", "
        caption = caption[:-2] # Remove final ", "

    ranking = get_ranked_results(rnd_complete)

    return render(request, 'kwis/ranking.html', {'sorted': ranking, 'caption': caption})

@login_required
def rnd_detail(request, rnd_id):
    """
    Detail views allow to view results per round or per team
    """
    rnd = get_object_or_404(QRound, pk=rnd_id)

    # Filter a list of answers for this round
    ar = rnd.qanswer_set.all()

    # Create a list of teams that don't have a score in this round yet
    team_list_todo = []
    for t in QTeam.objects.order_by('team_name'):
        if ar.filter(team = t).count() == 0:
            team_list_todo.append(t)
    # Teams that already have a score in this round can be accessed from the template using the _set

    # Create form to be used for all other teams
    form = ScoreForm(max_value=rnd.max_score)

    return render(request, 'kwis/rnd_detail.html', {'rnd': rnd, 'team_list_todo': team_list_todo, 'form': form})

@login_required
def team_detail(request, team_id):
    """
    Detail views allow to view results per round or per team
    """
    # Check if team entry exists
    team = get_object_or_404(QTeam, pk=team_id)

    # Count all results for this team
    subtotal = 0
    maxtotal = 0
    alist = team.qanswer_set.order_by('rnd')
    for a in alist:
        subtotal += a.score
        maxtotal += a.rnd.max_score

    # Create a list of rounds that have no results yet for this team
    round_list_todo = []
    for r in QRound.objects.all():
        if alist.filter(rnd = r).count() == 0:
            form = ScoreForm(max_value=r.max_score)
            round_list_todo.append((r, form))

    return render(request, 'kwis/team_detail.html', {'team': team, 'subtotal': subtotal, 'maxtotal': maxtotal, 'round_list_todo': round_list_todo})

@login_required
def vote(request, rnd_id, team_id):
    """
    The vote view handles the POST requests
    """
    # check for existing rnd and team
    arnd  = get_object_or_404(QRound, pk=rnd_id)
    ateam = get_object_or_404(QTeam, pk=team_id)

    # if item exists for QAnswer -> update; else create
    alist = QAnswer.objects.filter(rnd = arnd, team = ateam)
    if alist.count():
        a = alist.get()
    else:
        a = QAnswer(rnd = arnd, team = ateam, score="")

    # Get form
    if request.method == 'POST':
        form = PostedForm(request.POST)
        if form.is_valid():
            score= form.cleaned_data['score']

            # Primitive way to check correct value
            badvalue = 0
            if float(score) < 0 or float(score) > float(arnd.max_score):
                badvalue = 1

            if badvalue:
                form = ScoreForm(initial={'score': '0'})
            else:
                a.score = score
                a.save()

                return HttpResponseRedirect(reverse('kwis:rnd_detail', args=(arnd.id,)))

    else:
        form = ScoreForm(max_value=arnd.max_score, initial={'score': a.score})

    return render(request, 'kwis/form.html', {'rnd': arnd, 'team': ateam, 'form': form})

def team_result(request, team_id):
    """
    Plot results per team
    """

    # Retrieve team info and scores for the team
    ateam = get_object_or_404(QTeam, pk=team_id)
    answers = ateam.qanswer_set.order_by('rnd')

    # Set number of vertical bars
    ind = np.arange(len(answers))

    # Retrieve score, max score and name per round
    scores = [answer.score for answer in answers]
    maxima = [(answer.rnd.max_score - answer.score) for answer in answers]
    names  = [answer.rnd.round_name for answer in answers]

    # The image
    fig, ax = plt.subplots(1,1)
    fig.set_tight_layout(True)

    # Draw vertical bars
    width = 0.25
    ax.bar(ind, scores, width, color=colors['score_good'])
    ax.bar(ind, maxima, width, color=colors['score_bad'], bottom=scores)

    # Set labels and title
    ax.set_xticks(ind + width/2)
    ax.set_xticklabels(names)
    ax.set_xlabel(_("Rounds"))
    ax.set_ylabel(_("Scores"))

    title = _(u"Scores for %s") % ateam.team_name
    ax.set_title(title)

    ax.grid(True)
    canvas = FigureCanvas(fig)
    response = HttpResponse(content_type='image/png')

    canvas.print_png(response)
    return response

def rnd_result(request, rnd_id):
    """
    Plot results per round
    """

    # Retrieve round info and scores for round
    arnd = get_object_or_404(QRound, pk=rnd_id)
    answers = arnd.qanswer_set.order_by('-score')

    # Set number of vertical bars
    ind = np.arange(len(answers))

    # Retrieve score and team name per round
    scores = [answer.score for answer in answers]
    names  = [answer.team.team_name for answer in answers]

    # The image
    fig, ax = plt.subplots(1,1)
    fig.set_tight_layout(True)

    # Draw vertical bar
    width = 0.25
    ax.barh(ind, scores, width, color=colors['score_good'])

    # Set labels and title
    ax.set_yticks(ind + width/2)
    ax.set_yticklabels(names)
    ax.set_ylabel(_("Teams"))
    ax.set_xlabel(_("Scores"))

    title = _(u"Scores for %s") % arnd.round_name
    ax.set_title(title)

    ax.grid(True)

    canvas = FigureCanvas(fig)
    response = HttpResponse(content_type='image/png')

    canvas.print_png(response)
    return response

def team_overview(request):
    """
    Plot overview of all teams
    """

    # Cumulative scores per team
    ind = np.arange(QTeam.objects.count())

    subtotals = []
    maxtotals = []
    names     = []
    for t in QTeam.objects.all():
        subtotal = 0
        maxtotal = 0
        for ts in t.qanswer_set.all():
            subtotal += ts.score
            maxtotal += ts.rnd.max_score

kwis/templates/kwis/form.html
<!DOCTYPE html>
{% load i18n %}
<html>
  <head>
    {% include "kwis/headerContent.html" %}
  </head>
  <body>
    <div class="uk-container">
        <h1>{{ rnd.round_name }}</h1>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    
      <div class="uk-child-width-1-2@m" uk-grid>
      <div>
        <table class="table table-condensed table-striped">
          <caption>{% trans "Max score this round:" %} {{ rnd.max_score }}</caption>
          <thead>
          <tr>
            <th class="col-sm-4">{% trans "Team" %}</th>
            <th class="col-sm-4">{% trans "Score" %}</th>
            <th class="col-sm-4"></th>
          </tr>
          </thead>
          <tr>
            <form action="{% url 'kwis:vote' rnd.id team.id %}" method="post">
            {% csrf_token %}
            <td>
                <label><a href="{% url 'kwis:team_detail' team.id %}">{{ team.team_name }}</a></label>
            </td>
            <td>
              {{ form.score.errors }}
              {{ form.score }}
            </td>
            <td>
              <input type="submit" value="Enter" />
            </td>
            </form>
          </tr>
        </table>
      </div>
      </div>
    
      <HR>
      {% trans "Links:" %} <a href="{% url 'kwis:index' %}">{% trans "Index" %}</a>,
      <a href="{% url 'kwis:ranking' %}">{% trans "Ranking" %}</a>,
      <a href="/admin/">{% trans "Admin" %}</a>
    </div> <!-- /container -->
  </body>
</html>

kwis/templates/kwis/headerContent.html
    <title>Kwispel</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/css/uikit.min.css" />
    <script src="/static/js/uikit.min.js"></script>
    <script src="/static/js/uikit-icons.min.js"></script>
    <style>
    input[type="text"]{ width: 500px; }
    </style>

kwis/templates/kwis/index.html
<!DOCTYPE html>
{% load i18n %}
<html>
  <head>
    {% include "kwis/headerContent.html" %}
  </head>
  <body>
    <div class="uk-container">
      <div class="uk-child-width-1-2@m" uk-grid>
        <div>
        {% if round_list %}
          <table class="table table-condensed table-striped">
            <caption>{% trans "Overview of all rounds" %}</caption>
            <thead>
              <th>{% trans "Round" %}</th>
              <th>{% trans "Progress" %}</th>
            </thead>
            {% for round, status in round_list %}
            <tr>
              <td>
                <a href="{% url 'kwis:rnd_detail' round.id %}">{{ round.round_name }}</a>
              </td>
              <td>
               {{ status }}
              </td>
            </tr>
            {% endfor %}
          </table>

        {% else %}
          <p>{% trans "No rounds are available." %}</p>
        {% endif %}
        </div>
    
        <div>
        {% if team_list %}
          <table class="table table-condensed table-striped">
          <caption>{% trans "Overview of all teams" %}</caption>
            <thead>
              <th>{% trans "Team" %}</th>
              <th>{% trans "Progress" %}</th>
            </thead>
            {% for team, status, subtot in team_list %}
            <tr>
              <td>
                <a href="{% url 'kwis:team_detail' team.id %}">{{ team.team_name }}</a>
              </td>
              <td>
               {{ status }}
              </td>
            </tr>
            {% endfor %}
          </table>

        {% else %}
          <p>{% trans "No teams are available." %}</p>
        {% endif %}
        </div>

        <div>
          <a href="rnd_overview.png"><img class="img-responsive img-rounded center-block" src="rnd_overview.png" /></a>
        </div>
        <div>
          <a href="team_overview.png"><img class="img-responsive img-rounded center-block" src="team_overview.png" /></a>
        </div>
      </div> <!-- /grid -->

    <HR>
    {% trans "Links:" %} <a href="{% url 'kwis:ranking' %}">{% trans "Ranking" %}</a>, <a href="/admin/">{% trans "Admin" %}</a>
    </div> <!-- /container -->
  </body>
</html>

kwis/templates/kwis/ranking.html
<!DOCTYPE html>
{% load i18n %}
<html>
  <head>
{% include "kwis/headerContent.html" %}
    <meta http-equiv="refresh" content="60">
  </head>
  <body>
    <div class="uk-container uk-container-large">
    {% if sorted %}
      <div class="uk-text-lead uk-text-center">{{ caption }}</div>
      <div class="uk-child-width-1-2@m uk-grid-small" uk-grid>
        <div class="uk-card uk-card-default uk-card-body uk-text-lead uk-padding-small">
          <div uk-grid>
              <div class="uk-width-1-5 uk-text-right">{% trans "Place" %}</div>
              <div class="uk-width-3-5">{% trans "Team" %}</div>
              <div class="uk-width-1-5">{% trans "Score" %}</div>
          </div>
        </div>
        <div class="uk-visible@m uk-card uk-card-default uk-card-body uk-text-lead uk-padding-small">
          <div uk-grid>
              <div class="uk-width-1-5 uk-text-right">{% trans "Place" %}</div>
              <div class="uk-width-3-5">{% trans "Team" %}</div>
              <div class="uk-width-1-5">{% trans "Score" %}</div>
          </div>
        </div>
        {% for result in sorted %}
        <div class="uk-card uk-card-default uk-card-body uk-text-large uk-padding-small uk-padding-remove-vertical">
            <div uk-grid>
                <div class="uk-width-1-5 uk-text-right">{{ result.0 }}</div>
                <div class="uk-width-3-5">{{ result.1 }}</div>
                <div class="uk-width-1-5">{{ result.2 }}</div>
        </div>
        </div>
        {% endfor %}
      </div>
    {% else %}
      <p>{% trans "No sorted results found." %}</p>
    {% endif %}

    <HR>
    {% trans "Links:" %} <a href="{% url 'kwis:index' %}">{% trans "Index" %}</a>, <a href="/admin/">{% trans "Admin" %}</a>
    </div> <!-- /container -->
  </body>
</html>

kwis/templates/kwis/rnd_detail.html
<!DOCTYPE html>
{% load i18n %}
<html>
  <head>
    {% include "kwis/headerContent.html" %}
  </head>
  <body>
    <div class="uk-container">
        <h1>{{ rnd.round_name }}</h1>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    
      <div class="uk-child-width-1-2@m" uk-grid>
      <div>
        <table class="table table-condensed table-striped">
          <caption>{% trans "Max score this round:" %} {{ rnd.max_score }}</caption>
          <thead>
          <tr>
            <th class="col-sm-4">{% trans "Team" %}</th>
            <th class="col-sm-4">{% trans "Score" %}</th>
            <th class="col-sm-4"></th>
          </tr>
          </thead>
          {% for team in team_list_todo %}
          <tr>
            <form action="{% url 'kwis:vote' rnd.id team.id %}" method="post">
            {% csrf_token %}
            <td>
              <label><a href="{% url 'kwis:team_detail' team.id %}">{{ team.team_name }}</a></label>
            </td>
            <td>
              {{ form.score }}
            <td>
            <input type="submit" value="Enter" />
            </form>
          </tr>
          {% endfor %}
    
          {% for answer in rnd.qanswer_set.all %}
          <tr>
            <td>
              <a href="{% url 'kwis:team_detail' answer.team.id %}">{{ answer.team.team_name }}</a>
            </td>
            <td>
              <a href="{% url 'kwis:vote' answer.rnd.id answer.team.id %}">{{ answer.score }}</a>
            </td>
            <td>
            </td>
          </tr>
          {% endfor %}
        </table>
      </div>

      <div>
        <div><img class="img-responsive img-rounded center-block" src="result.png" /></div>
      </div>
      </div>

      <HR>
      {% trans "Links:" %} <a href="{% url 'kwis:index' %}">{% trans "Index" %}</a>,
      <a href="{% url 'kwis:ranking' %}">{% trans "Ranking" %}</a>,
      <a href="/admin/">{% trans "Admin" %}</a>
    </div> <!-- /container -->
  </body>
</html>

kwis/templates/kwis/team_detail.html
<!DOCTYPE html>
{% load i18n %}
<html>
  <head>
    {% include "kwis/headerContent.html" %}
  </head>
  <body>
    <div class="uk-container">
        <h1>{{ team.team_name }}</h1>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    
      <div class="uk-child-width-1-2@m" uk-grid>
      <div>
        <table class="table table-condensed table-striped">
		<caption>{% trans "Subtotal:" %} {{ subtotal }} / {{ maxtotal }}</caption>
          <thead>
          <tr>
            <th class="col-sm-4">{% trans "Round" %}</th>
            <th class="col-sm-4">{% trans "Score" %}</th>
            <th class="col-sm-4"></th>
          </tr>
          </thead>
          {% for answer in team.qanswer_set.all %}
          <tr>
            <td>
              <a href="{% url 'kwis:rnd_detail' answer.rnd.id %}">{{ answer.rnd.round_name }}</a>
            </td>
            <td>
              <a href="{% url 'kwis:vote' answer.rnd.id answer.team.id %}">{{ answer.score }}</a>
            </td>
            <td>
            </td>
          </tr>
          {% endfor %}
          {% for rnd, form in round_list_todo %}
          <tr>
            <form action="{% url 'kwis:vote' rnd.id team.id %}" method="post">
            {% csrf_token %}
            <td>
              <label><a href="{% url 'kwis:rnd_detail' rnd.id %}">{{ rnd.round_name }}</a></label>
            </td>
            <td>
              {{ form.score }}
            <td>
            <input type="submit" value="Enter" />
            </form>
          </tr>
          {% endfor %}
        </table>
      </div>

      <div class="span4"><img class="img-responsive img-rounded center-block" src="result.png" /></div>
      </div>

      <HR>
      {% trans "Links:" %} <a href="{% url 'kwis:index' %}">{% trans "Index" %}</a>,
      <a href="{% url 'kwis:ranking' %}">{% trans "Ranking" %}</a>,
      <a href="/admin/">{% trans "Admin" %}</a>
    </div> <!-- /container -->
  </body>
</html>